<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>supervisord.conf</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#supervisord$</string>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Supervisord</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\[[\w:]+\]|%\(\w+\)s</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.supervisord-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-supervisord-config</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>punctuation.separator.key-value.supervisord-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*[a-zA-Z][0-9a-zA-Z._-]*</string>
			<key>name</key>
			<string>support.constant.name.supervisord-config</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.supervisord-config</string>
	<key>uuid</key>
	<string>E024D04B-916E-4DA0-A8F0-BB26790E2D78</string>
</dict>
</plist>
